services:
  database:
    image: postgres:16-alpine
    container_name: si_p2_database
    environment:
      POSTGRES_DB: videoclub
      POSTGRES_USER: si_user
      POSTGRES_PASSWORD: si_password
    ports:
      - "5432:5432"
    volumes:
      - p2_database_data:/var/lib/postgresql/data
      - ./database/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql:ro
      - ./database/populate.sql:/docker-entrypoint-initdb.d/02-populate.sql:ro
    restart: unless-stopped

volumes:
  p2_database_data:
